events {}

http {

    server {
        listen 80;
        server_name localhost;

        # Redirigir todo HTTP a HTTPS
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/certs/dev.crt;
        ssl_certificate_key /etc/nginx/certs/dev.key;

        ssl_protocols TLSv1.2 TLSv1.3;

        location / {
            proxy_pass http://frontend:3000;
        }

        location /api/ {
            proxy_pass http://backend:8080/;
        }

        location /ai/ {
            proxy_pass http://ai-service:8000/;
        }
    }
}